[features]
seeds = false
skip-lint = false
[programs.localnet]
ammanexample = "6UoJe8pdk1dBdCW1FXf1Tc6GxfZVrBLNS7ijUhYSZu2m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/devenv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
